name: pokemon_guessing_game
description: A Pokemon guessing game using PokeAPI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^1.1.0
  cached_network_image: ^3.3.0
  image: ^4.1.3
  shared_preferences: ^2.2.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  google_sign_in: ^6.3.0
  intl: ^0.19.0
  firebase_app_check: ^0.3.2+5
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 