// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR__MlzwiRXk4G9b5VB1XLuYW07Dw1Iuw',
    appId: '1:333518557427:web:d379d3a7b188acbea96786',
    messagingSenderId: '333518557427',
    projectId: 'petkun-pokemon-project',
    authDomain: 'petkun-pokemon-project.firebaseapp.com',
    storageBucket: 'petkun-pokemon-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdRhGWKU6PJo0LYfQkT4Da-4lbvHi6kzY',
    appId: '1:333518557427:android:06bdcc95d7e4d4f1a96786',
    messagingSenderId: '333518557427',
    projectId: 'petkun-pokemon-project',
    storageBucket: 'petkun-pokemon-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPDIqL1Qenqrd3Kk686_bhRpMJ9JBNwDw',
    appId: '1:333518557427:ios:8fe28287e72bbde1a96786',
    messagingSenderId: '333518557427',
    projectId: 'petkun-pokemon-project',
    storageBucket: 'petkun-pokemon-project.firebasestorage.app',
    iosBundleId: 'com.example.pokemonGuessingGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPDIqL1Qenqrd3Kk686_bhRpMJ9JBNwDw',
    appId: '1:333518557427:ios:8fe28287e72bbde1a96786',
    messagingSenderId: '333518557427',
    projectId: 'petkun-pokemon-project',
    storageBucket: 'petkun-pokemon-project.firebasestorage.app',
    iosBundleId: 'com.example.pokemonGuessingGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR__MlzwiRXk4G9b5VB1XLuYW07Dw1Iuw',
    appId: '1:333518557427:web:f09150af8e859d6da96786',
    messagingSenderId: '333518557427',
    projectId: 'petkun-pokemon-project',
    authDomain: 'petkun-pokemon-project.firebaseapp.com',
    storageBucket: 'petkun-pokemon-project.firebasestorage.app',
  );

}